apiVersion: v1
kind: Service
metadata:
  name: messageboard-service
  labels:
    app: messageboard
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30003
  selector:
    app: messageboard
  sessionAffinity: ClientIP
