apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: messageboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: messageboard
        version: "1.JENKINS_BUILD_VERSION_NUMBER"
    spec:
      containers:
        - name: messageboard
          image: donjwhite1/messageboard
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/catalina
            - name: gluster-volume
              mountPath: /media
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /MessageBoard-1.0-SNAPSHOT
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: config-volume
          configMap:
            name: messageboard
        - name: gluster-volume
          nfs:
            path: /export
            server: 10.131.24.152
